backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
  branch: master # Branch to update (optional; defaults to master)
media_folder: "images/" # Media files will be stored in the repo under images/uploads
public_folder: "/"
collections:
  - name: "team" # Used in routes, e.g., /admin/collections/blog
    label: "Team" # Used in the UI
    folder: "_team" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "team"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Job title", name: "jobtitle", widget: "string"}
      - {label: "linkedin", name: "linkedinurl", widget: "string"}
      - {label: "weight", name: "weight", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "services" # Used in routes, e.g., /admin/collections/blog
    label: "Services" # Used in the UI
    folder: "_services" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "services"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "weight", name: "weight", widget: "number"}
  - name: contacts
    label: Contacts
    files:
      - label: "Contact"
        name: "contact"
        file: "_data/contact.yml"
        fields:
          - {label: Email, name: email, widget: string}
          - {label: Phone, name: phone, widget: string}
          - {label: Contact button link, name: contact_button_link, widget: string}
      - label: "SEO"
        name: "seo"
        file: "_data/seo.yml"
        fields:
          - {label: google_analytics_id, name: google_analytics_id, widget: string}
          - {label: meta_twitter_site, name: meta_twitter_site, widget: string}
          - {label: meta_twitter_creator, name: meta_twitter_creator, widget: string}          
          - {label: copyright_text, name: copyright_text, widget: string}          
  - name: "json"
    label: "json"
    files:
      - label: "Extra"
        name: "extra"
        file: "_data/data.json"
        format: "json"
        fields:
          - label: "features"
            name: "features"
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: string}
              - label: Image
                name: image
                widget: object
                fields:
                  - {label: URL, name: url, widget: string}
                  - {label: Width, name: width, widget: number}
                  - {label: Height, name: height, widget: number}
          - label: "Social"
            name: "social"
            widget: list
            create: true
            fields:
              - {label: name, name: name, widget: string}
              - {label: Link, name: link, widget: string}
              - {label: image, name: image, widget: string}
